### ISSUE TITLE
Model checkpoints or Architecture

### ISSUE THREAD

**Issue by ferdavid1** [hayeong0/DDDM-VC#1]
Could you share the codebase you have? Even as-is. I am very interested in recreating your work :)

**Comment by hayeong0** [comment]
Thanks for your interest in our work.  
We will have them organized and uploaded over the weekend :)

**Comment by mysxs** [comment]
When will the training code be made available? thanks!  :)

**Comment by hayeong0** [comment]
Thanks for showing interest in our work. I plan to share the training code within January :)

**Comment by seshi114** [comment]
How is it going now? Will I have the training code by the end of the month? Thanks!
