### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by wlf0322** [hayeong0/DDDM-VC#10]
训练时候报错：不知道你有没有遇到过
OSError: libavutil.so.56: cannot open shared object file: No such file or directory
DEBUG:torio._extension.utils:Loading FFmpeg
DEBUG:torio._extension.utils:Failed to load FFmpeg extension.

**Comment by hayeong0** [comment]
It looks like FFmpeg is either not installed or the path cannot be found. 
Please check the installation.

For Ubuntu/Linux:
```
sudo apt install ffmpeg
```
