### ISSUE TITLE
Model is not converging even after 50+ epochs!

### ISSUE THREAD

**Issue by Ashigarg123** [hayeong0/DDDM-VC#11]

**Comment by hayeong0** [comment]
I have trained a model for over 200 epochs with a batch size of 64, using the LibriTTS-100 and 360 datasets. 
From my experience with training diffusion-based VC models, I have observed that sufficient training is necessary, and the LR, depending on the batch size, also affects the convergence of the training.

**Comment by Ashigarg123** [comment]
Thank you, it performs well. I was looking at the loss printed for each epoch. However, results after performing inference with a saved checkpoint looks good.
