### ISSUE TITLE
DDDM-TTS

### ISSUE THREAD

**Issue by csu-roycheng** [hayeong0/DDDM-VC#13]
Thanks for your great work! 

I am very interested in DDDM-TTS model, will you open source the code?

**Comment by hayeong0** [comment]
Thank you for your interest in our work.

You can replace the content (w2v) of the DDDM-VC model with the Text-to-Vec part of DDDM-TTS, which encodes text into w2v. 

We currently have no plans to release DDDM-TTS additionally, but you can use the [ttv code](https://github.com/sh-lee-prml/HierSpeechpp/tree/main/ttv_v1) available in our subsequent project, the HierSpeech++ repository.

Thanks!

**Comment by csu-roycheng** [comment]
> Thank you for your interest in our work.
> 
> You can replace the content (w2v) of the DDDM-VC model with the Text-to-Vec part of DDDM-TTS, which encodes text into w2v.
> 
> We currently have no plans to release DDDM-TTS additionally, but you can use the [ttv code](https://github.com/sh-lee-prml/HierSpeechpp/tree/main/ttv_v1) available in our subsequent project, the HierSpeech++ repository.
> 
> Thanks!

Thanks for your reply!

I found "mms-300m" was used in hierspeech, and "XLS-R" was used in DDDM to extract self-supervised speech representation. I would like to know whether these two methods have a significant impact on the result.

**Comment by hayeong0** [comment]
@csu-roycheng 

After XLS-R, MMS was released, covering more languages. We trained the model by replacing the module with MMS, achieving slightly better performance in English. 
Also, We're now using MMS in our subsequent research to enhance multi/cross-lingual scalability!
