### ISSUE TITLE
training on VCTK

### ISSUE THREAD

**Issue by Aydous** [hayeong0/DDDM-VC#16]
Hello,I trianed DDDM-VC on VCTK. The audio quality is poor. Is it normal? The loss on tensorboard is shown below.
<img width="759" alt="loss" src="https://github.com/user-attachments/assets/f222547b-3ff4-4c02-9cf7-707d7665f942">

**Comment by hayeong0** [comment]
I have replied to your email with the answer to your question.  
If you have any questions, please feel free to open an issue.
