### ISSUE TITLE
Request on details of the data augmentation module

### ISSUE THREAD

**Issue by kur114** [hayeong0/DDDM-VC#2]
Hello, I am in the process of training a model and find myself uncertain about the specifics of the data augmentation module. Here are two questions:

1. Is the module implemented using this code: https://github.com/revsic/torch-nansypp/blob/main/utils/augment?
2. Could you specify which hyperparameters in your configuration are passed to the augmentation module?

Thank you for your reply!

**Comment by hayeong0** [comment]
Hello, thank you for showing interest in our work. 
I have updated the augmentation code that I used for this work, so please refer to it:
- https://github.com/hayeong0/DDDM-VC/tree/master/augmentation
 
We also used the hyperparameter ratio proposed by NANSY, and observed that other values yielded worse or similar results, so we used the same hyperparameter. Specifically, it is as follows:
- Formant shifting: U(1, 1.4)
- Pitch randomization: U(1, 2)
- random frequency shaping: (1, 1.5)

**Comment by kur114** [comment]
Thank you very much for your detailed and helpful response. Your detailed implementation code has significantly clarified my understanding and will greatly assist me in my model training efforts.
