### ISSUE TITLE
请问怎么微调训练，我看到缺少一些模型，例如：'./hifigan/G_2930000.pth'

### ISSUE THREAD

**Issue by wlf0322** [hayeong0/DDDM-VC#3]

**Comment by hayeong0** [comment]
Hello, the vocoder ckpt mentioned in the training code has already been updated to the hifigan vocoder checkpoint.
So, you can modify the path accordingly to use it. Thanks.

**Comment by Ashigarg123** [comment]
Does 'voc_ckpt.pth' in drive folder refers to hifigan checkpoint?
